config/routes.rb
Rails.application.routes.draw do
  resources :categories
  get 'archives/index'
  resources :entries
  root 'entries#index'

  resources :categories
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :entries
end

app/models/entry.rb
class Entry < ApplicationRecord
  belongs_to :category

  validates :calories, :proteins, :carbohydrates, :fats, :meal_type, :category_id, presence: true
  def day
    created_at.strftime('%b, %e, %y')
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/archives_controller.rb
class ArchivesController < ApplicationController
  def index
    @entries = Entry.all.group_by(&:day)
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_category, only: %i[show edit update destroy]

  # GET /categories or /categories.json
  def index
    @categories = Category.all
  end

  # GET /categories/1 or /categories/1.json
  def show; end

  # GET /categories/new
  def new
    @category = Category.new
  end

  # GET /categories/1/edit
  def edit; end

  # POST /categories or /categories.json
  def create
    @category = Category.new(category_params)

    respond_to do |format|
      if @category.save
        format.html { redirect_to category_url(@category), notice: 'Category was successfully created.' }
        format.json { render :show, status: :created, location: @category }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /categories/1 or /categories/1.json
  def update
    respond_to do |format|
      if @category.update(category_params)
        format.html { redirect_to category_url(@category), notice: 'Category was successfully updated.' }
        format.json { render :show, status: :ok, location: @category }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /categories/1 or /categories/1.json
  def destroy
    @category.destroy

    respond_to do |format|
      format.html { redirect_to categories_url, notice: 'Category was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_category
    @category = Category.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def category_params
    params.require(:category).permit(:title)
  end
end

app/controllers/entries_controller.rb
class EntriesController < ApplicationController
  before_action :set_entry, only: %i[show edit update destroy]

  # GET /entries or /entries.json
  def index
    @entries = Entry.where('created_at >= ?', Date.today)
  end

  # GET /entries/1 or /entries/1.json
  def show; end

  # GET /entries/new
  def new
    @entry = Entry.new
  end

  # GET /entries/1/edit
  def edit; end

  # POST /entries or /entries.json
  def create
    @entry = Entry.new(entry_params)

    respond_to do |format|
      if @entry.save
        format.html { redirect_to entry_url(@entry), notice: 'Entry was successfully created.' }
        format.json { render :show, status: :created, location: @entry }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @entry.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /entries/1 or /entries/1.json
  def update
    respond_to do |format|
      if @entry.update(entry_params)
        format.html { redirect_to entry_url(@entry), notice: 'Entry was successfully updated.' }
        format.json { render :show, status: :ok, location: @entry }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @entry.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /entries/1 or /entries/1.json
  def destroy
    @entry.destroy

    respond_to do |format|
      format.html { redirect_to entries_url, notice: 'Entry was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_entry
    @entry = Entry.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def entry_params
    params.require(:entry).permit(:meal_type, :calories, :proteins, :carbohydrates, :fats, :category_id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/archives_helper.rb
module ArchivesHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/entries_helper.rb
module EntriesHelper
end

app/views/archives/index.html.erb
<div class="columns is-centered mt-6">
  <div class="column is-half">
    <% @entries.each do |day, entries| %>
      <h3 class="has-text-weight-bold mb-4 mt-5 has-text-centered"> 
        Entries for <%= day%> 
      </h3>
      <nav class="level is-mobile">
        <div class="level-tem has-text-centered">
          <div>
            <p class="heading">Calories</p>
            <p class="title"><%= entries.pluck(:calories).sum%></p>
          </div>
        </div>
           <div class="level-tem has-text-centered">
          <div>
            <p class="heading">Proteins</p>
            <p class="title"><%= entries.pluck(:proteins).sum%>g</p>
          </div>
        </div>
        <div class="level-tem has-text-centered">
          <div>
            <p class="heading">Carbohydrates</p>
            <p class="title"><%= entries.pluck(:carbohydrates).sum%>g</p>
          </div>
        </div>
        <div class="level-tem has-text-centered">
          <div>
            <p class="heading">Fats</p>
            <p class="title"><%= entries.pluck(:fats).sum%>g</p>
          </div>
        </div>
      </nav>
      <% entries.each do |entry|%>
        <%= link_to entry_path(entry) do %>
          <div class="card">
            <div class="card-content">
              <strong><%= entry.meal_type %></strong><br/>
              <%= entry.calories %> Calories,
              <%= entry.proteins %> g Protein,
              <%= entry.carbohydrates %> g Carbs,
              <%= entry.fats %> g Fats
            </div>
          </div>
        <%end%>
      <%end%>
    <%end%>
  </div>
</div>

app/views/categories/_category.html.erb
<div id="<%= dom_id category %>">
  <p class="column has-text-centered">
    <strong>Title:
    <%= category.title %>
    </strong>
  </p>

</div>

app/views/categories/_form.html.erb
<%= form_with(model: category) do |form| %>
  <% if category.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(category.errors.count, "error") %> prohibited this category from being saved:</h2>

      <ul>
        <% category.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title, class: "label" %>
    <%= form.text_field :title, class: "input"%>
  </div>

  <div>
    <%= form.submit class: "button is-success" %>
  </div>
<% end %>

app/views/categories/edit.html.erb
<div class="columns is-centered mt-6">
  <div class="column is-one-third">
    <h1 class="is-size-2 has-text-weight-bold mb-3">Editing category</h1>
    <%= render "form", category: @category %>
  </div>
</div>

app/views/categories/index.html.erb
<% content_for :title do %>
  Categories &ndash; <%= DateTime.now.strftime("%B %e, %Y") %>
<%end%>
<div class="columns mt-6 is-centered">
  <% @categories.each do |category| %>
    <div class="column is-one-quarter">
      <div class="card">
        <%= render category %>
      <div class="card-footer">
          <%= link_to "Edit", edit_category_path(category), class: "card-footer-item" %>
          <%= link_to "Delete", category_path(category), data: { turbo_method: :delete, turbo_confirm: "Are you  sure?"}, class: "card-footer-item" %>
      </div>
      </div>
    </div>
  <% end %>
</div>
<div class="column has-text-centered">
<%= link_to "New category", new_category_path, class:"button is-primary" %>
</div>

app/views/categories/new.html.erb
<div class="columns is-centered mt-6">
  <div class="column is-one-third">
      <h1 class="is-size-2 has-text-weight-bold mb-3">New Category</h1>
        <%= render "form", category: @category %>
  </div>

</div>
<div class="column is-centered is-one-third">
  <%= link_to "Back to categories", categories_path, class:"button is-link" %>
</div>

app/views/categories/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @category %>

<div>
  <%= link_to "Edit this category", edit_category_path(@category) %> |
  <%= link_to "Back to categories", categories_path %>

  <%= button_to "Destroy this category", @category, method: :delete %>
</div>

app/views/entries/_entry.html.erb
  <header class="card-header">
    <p class="card-header-title"><%= entry.meal_type %> | <%= entry.category.title  if entry.category.present?%>
  </header>

  <div class="card-content">
    <div class="content">
      <p><span class="has-text-weight-bold"><%= entry.calories %></span> Calories</p>
      <p><span class="has-text-weight-bold"> <%= entry.proteins %></span> Grams of Protien</p>
      <p><span class="has-text-weight-bold"><%= entry.carbohydrates %></span> Grams of Carbohydrates</p>
      <p><span class="has-text-weight-bold"><%= entry.fats %></span> Grams of Fat</p>
      <p class="italic">Logged <%= time_ago_in_words(entry.created_at)%> ago</p>
    </div>
  </div>

app/views/entries/_form.html.erb
<%= form_with(model: entry) do |form| %>
  <% if entry.errors.any? %>
    <div class="message is-danger">
      <div class="message-header">
        <p><%= pluralize(entry.errors.count, "error") %> prohibited this entry from being saved:</p>
      </div>
      <div class="message-body">
        <ul>
          <% entry.errors.each do |error| %>
            <li><%= error.full_message %></li>
          <% end %>
        </ul>
      </div>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :meal_type, class: "label" %>
    <%= form.text_field :meal_type, class: "input" %>
  </div>

  <div class="field">
    <%= form.label :calories,  class: "label" %>
    <%= form.number_field :calories, class: "input" %>
  </div>

  <div class="field">
    <%= form.label :proteins,  class: "label" %>
    <%= form.number_field :proteins, class: "input" %>
  </div>

  <div class="field">
    <%= form.label :carbohydrates,  class: "label" %>
    <%= form.number_field :carbohydrates, class: "input" %>
  </div>

  <div class="field">
    <%= form.label :fats, class: "label"%>
     <%= form.number_field :fats, class: "input"  %>
 </div>


  <div class="field">
    <%= form.label :category_id,  class: "label" %>
    <div class="select">
      <%= form.select :category_id, Category.all.collect {|c| [c.title, c.id]}%>
    </div>
  </div>

  <div>
    <%= form.submit class: "button is-success" %>
  </div>
<% end %>

app/views/entries/edit.html.erb
<div class="columns is-centered mt-6">
  <div class="column is-one-third">
    <h1 class="is-size-2 has-text-weight-bold mb-3">Editing entry</h1>
    <%= render "form", entry: @entry %>
  </div>
</div>

app/views/entries/index.html.erb
<% content_for :title do %>
  Foodlog &ndash; <%= DateTime.now.strftime("%B %e, %Y") %>
<%end%>
<div class="columns mt-6 is-centered is-multiline">
  <% @entries.each do |entry| %>
    <div class="column is-one-quarter">
      <div class="card">
        <%= render entry %>
      <div class="card-footer">
          <%= link_to "Show", entry, class: "card-footer-item" %>
          <%= link_to "Edit", edit_entry_path(entry), class: "card-footer-item" %>
          <%= link_to "Delete", entry_path(entry), data: { turbo_method: :delete, turbo_confirm: "Are you  sure?"}, class: "card-footer-item" %>
      </div>
      </div>
    </div>
  <% end %>
</div>

<div class="column has-text-centered mt-6">
  <%= link_to "View all entries", archives_index_path, class: "button is-link is-outlined"%>
</div>

app/views/entries/new.html.erb
<div class="columns is-centered mt-6">
  <div class="column is-one-third">
    <h1 class="is-size-2 has-text-weight-bold mb-3">New entry</h1>
    <%= render "form", entry: @entry %>
  </div>
</div>

app/views/entries/show.html.erb
<% content_for :title do %>
  <%= @entry.meal_type %>&ndash; <%= DateTime.now.strftime("%B %e, %Y") %>
<%end%>

<div class="columns is-centered mt-6">
  <div class="column is-one-third">
    <nav class="panel is-link ">
      <p class="panel-heading">
        <%= @entry.meal_type  %> | <%= @entry.category.title  if @entry.category.present?%>   </p>
      <div class="panel-block">
        Calories: <%= @entry.calories %>
      </div>

      <div class="panel-block">
        Proteins: <%= @entry.proteins %>
      </div>

      <div class="panel-block">
        Carbohydrates: <%= @entry.carbohydrates %>
      </div>

      <div class="panel-block">
        Fats: <%= @entry.fats %>
      </div>
  </nav>

  <div class="columns is-mobile">
    <div class="column">
      <%= link_to "Edit", edit_entry_path(@entry), class: "button is-gray" %>
      <%= link_to "Delete", entry_path(@entry), data: { turbo_method: :delete, turbo_confirm: "Are you  sure?"}, class: "button is-danger" %>
    </div>
  </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Foodlog</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bulma@0.9.4/css/bulma.min.css">
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <link rel="shortcut icon" type="image/x-icon" href="<%= asset_path 'favicon.ico' %>">
  </head>

  <body class="m-3">
  
  <%= render 'shared/header'%>
  <% if notice.present? %>
    <div class="notification columns is-centered is-link is-light center"><%= notice %></div>
  <% end %>


  <% if alert.present? %>
      <div class="notification columns is-centered is-danger is-light"><%= alert %></div>
  <% end %>
  <div class="container">
    <%= yield %>
  </div>
  </body>
</html>

app/views/shared/_header.html.erb
<nav class="navbar" role="navigation" aria-label="main navigation">
  <div class="navbar-brand">
    <%= link_to root_path, class: "navbar-item" do %>
    <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 448 512" width="30" class="has-text-white has-background-white" height="30"><path d="M416 0C400 0 288 32 288 176V288c0 35.3 28.7 64 64 64h32V480c0 17.7 14.3 32 32 32s32-14.3 32-32V352 240 32c0-17.7-14.3-32-32-32zM64 16C64 7.8 57.9 1 49.7 .1S34.2 4.6 32.4 12.5L2.1 148.8C.7 155.1 0 161.5 0 167.9c0 45.9 35.1 83.6 80 87.7V480c0 17.7 14.3 32 32 32s32-14.3 32-32V255.6c44.9-4.1 80-41.8 80-87.7c0-6.4-.7-12.8-2.1-19.1L191.6 12.5c-1.8-8-9.3-13.3-17.4-12.4S160 7.8 160 16V150.2c0 5.4-4.4 9.8-9.8 9.8c-5.1 0-9.3-3.9-9.8-9L127.9 14.6C127.2 6.3 120.3 0 112 0s-15.2 6.3-15.9 14.6L83.7 151c-.5 5.1-4.7 9-9.8 9c-5.4 0-9.8-4.4-9.8-9.8V16zm48.3 152l-.3 0-.3 0 .3-.7 .3 .7z"/></svg>
    <span class="ml-3 title has-text-primary">Foodlog</span>
    <% end %>

    <a role="button" class="navbar-burger" aria-label="menu" aria-expanded="false" data-target="navbarBasicExample">
      <span aria-hidden="true"></span>
      <span aria-hidden="true"></span>
      <span aria-hidden="true"></span>
    </a>
  </div>

  <div id="navbarBasicExample" class="navbar-menu">
    <div class="navbar-start">
    </div>

    <div class="navbar-center">
      <div class="navbar-item">
        <div class="title">
          <% if content_for(:title)%>
            <%= yield :title %>
          <% else %>
            Foodlog
          <%end%>
        </div>
       </div>
    </div>

    <div class="navbar-end">
     <div class="navbar-item">
        <%= link_to "Categories", categories_path, class: "button is-link"%>
      </div>
      <div class="navbar-item">
        <%= link_to "New Meal", new_entry_path, class: "button is-link"%>
      </div>
    </div>
  </div>
</nav>